/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Sat Feb 25 03:26:04 2017. */

#include "app.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TaskMessage_fields[6] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, TaskMessage, header, header, &BaseHeader_fields),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, TaskMessage, name_len, header, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, TaskMessage, pct, name_len, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, TaskMessage, name, pct, 0),
    PB_FIELD(  5, BOOL    , REQUIRED, STATIC  , OTHER, TaskMessage, is_last, name, 0),
    PB_LAST_FIELD
};

const pb_field_t SensorsMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, SensorsMessage, header, header, &BaseHeader_fields),
    PB_LAST_FIELD
};

const pb_field_t KnockMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, KnockMessage, header, header, &BaseHeader_fields),
    PB_LAST_FIELD
};

const pb_field_t SettingsMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, SettingsMessage, header, header, &BaseHeader_fields),
    PB_LAST_FIELD
};

const pb_field_t TableMessage_fields[5] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, TableMessage, header, header, &BaseHeader_fields),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, TableMessage, id, header, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, TableMessage, len, id, 0),
    PB_FIELD(  4, BYTES   , REQUIRED, STATIC  , OTHER, TableMessage, data, len, 0),
    PB_LAST_FIELD
};

const pb_field_t CellMessage_fields[5] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, CellMessage, header, header, &BaseHeader_fields),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, CellMessage, row, header, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, CellMessage, column, row, 0),
    PB_FIELD(  4, BYTES   , REQUIRED, STATIC  , OTHER, CellMessage, value, column, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TaskMessage, header) < 65536 && pb_membersize(SensorsMessage, header) < 65536 && pb_membersize(KnockMessage, header) < 65536 && pb_membersize(SettingsMessage, header) < 65536 && pb_membersize(TableMessage, header) < 65536 && pb_membersize(CellMessage, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_TaskMessage_SensorsMessage_KnockMessage_SettingsMessage_TableMessage_CellMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TaskMessage, header) < 256 && pb_membersize(SensorsMessage, header) < 256 && pb_membersize(KnockMessage, header) < 256 && pb_membersize(SettingsMessage, header) < 256 && pb_membersize(TableMessage, header) < 256 && pb_membersize(CellMessage, header) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_TaskMessage_SensorsMessage_KnockMessage_SettingsMessage_TableMessage_CellMessage)
#endif


/* @@protoc_insertion_point(eof) */
