/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8-dev at Wed Feb 22 21:00:01 2017. */

#ifndef PB_BASE_PB_H_INCLUDED
#define PB_BASE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _BaseHeader {
    char magic[3];
    char cmd[20];
    uint32_t len;
/* @@protoc_insertion_point(struct:BaseHeader) */
} BaseHeader;

typedef struct _Crc {
    uint32_t crc;
/* @@protoc_insertion_point(struct:Crc) */
} Crc;

typedef PB_BYTES_ARRAY_T(200) BaseRequest_data_t;
typedef struct _BaseRequest {
    BaseHeader header;
    bool has_data;
    BaseRequest_data_t data;
    Crc crc;
/* @@protoc_insertion_point(struct:BaseRequest) */
} BaseRequest;

/* Default values for struct fields */
extern const uint32_t BaseHeader_len_default;
extern const uint32_t Crc_crc_default;

/* Initializer values for message structs */
#define BaseHeader_init_default                  {"", "", 0u}
#define Crc_init_default                         {0u}
#define BaseRequest_init_default                 {BaseHeader_init_default, false, {0, {0}}, Crc_init_default}
#define BaseHeader_init_zero                     {"", "", 0}
#define Crc_init_zero                            {0}
#define BaseRequest_init_zero                    {BaseHeader_init_zero, false, {0, {0}}, Crc_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define BaseHeader_magic_tag                     1
#define BaseHeader_cmd_tag                       2
#define BaseHeader_len_tag                       3
#define Crc_crc_tag                              1
#define BaseRequest_header_tag                   1
#define BaseRequest_data_tag                     2
#define BaseRequest_crc_tag                      3

/* Struct field encoding specification for nanopb */
extern const pb_field_t BaseHeader_fields[4];
extern const pb_field_t Crc_fields[2];
extern const pb_field_t BaseRequest_fields[4];

/* Maximum encoded size of messages (where known) */
#define BaseHeader_size                          33
#define Crc_size                                 6
#define BaseRequest_size                         246

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BASE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
