/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8-dev at Fri Feb 24 18:49:14 2017. */

#ifndef PB_BASE_PB_H_INCLUDED
#define PB_BASE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _BaseHeader {
    char magic[6];
    uint32_t cmd;
/* @@protoc_insertion_point(struct:BaseHeader) */
} BaseHeader;

typedef struct _Crc {
    uint32_t poly;
    uint32_t val;
/* @@protoc_insertion_point(struct:Crc) */
} Crc;

typedef struct _BaseRequest {
    BaseHeader header;
    Crc crc;
/* @@protoc_insertion_point(struct:BaseRequest) */
} BaseRequest;

typedef struct _BaseResponse {
    BaseHeader header;
    uint32_t code;
    Crc crc;
/* @@protoc_insertion_point(struct:BaseResponse) */
} BaseResponse;

/* Default values for struct fields */
extern const uint32_t BaseHeader_cmd_default;
extern const uint32_t Crc_poly_default;
extern const uint32_t Crc_val_default;

/* Initializer values for message structs */
#define BaseHeader_init_default                  {"", 0u}
#define Crc_init_default                         {79764919u, 0u}
#define BaseRequest_init_default                 {BaseHeader_init_default, Crc_init_default}
#define BaseResponse_init_default                {BaseHeader_init_default, 0, Crc_init_default}
#define BaseHeader_init_zero                     {"", 0}
#define Crc_init_zero                            {0, 0}
#define BaseRequest_init_zero                    {BaseHeader_init_zero, Crc_init_zero}
#define BaseResponse_init_zero                   {BaseHeader_init_zero, 0, Crc_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define BaseHeader_magic_tag                     1
#define BaseHeader_cmd_tag                       2
#define Crc_poly_tag                             1
#define Crc_val_tag                              2
#define BaseRequest_header_tag                   1
#define BaseRequest_crc_tag                      2
#define BaseResponse_header_tag                  1
#define BaseResponse_code_tag                    2
#define BaseResponse_crc_tag                     3

/* Struct field encoding specification for nanopb */
extern const pb_field_t BaseHeader_fields[3];
extern const pb_field_t Crc_fields[3];
extern const pb_field_t BaseRequest_fields[3];
extern const pb_field_t BaseResponse_fields[4];

/* Maximum encoded size of messages (where known) */
#define BaseHeader_size                          14
#define Crc_size                                 12
#define BaseRequest_size                         30
#define BaseResponse_size                        36

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BASE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
