/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8-dev at Wed Feb 22 21:00:01 2017. */

#ifndef PB_BOOTLOADER_PB_H_INCLUDED
#define PB_BOOTLOADER_PB_H_INCLUDED
#include <pb.h>

#include "base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(200) FlashReadRequest_data_t;
typedef struct _FlashReadRequest {
    BaseHeader header;
    uint32_t addr;
    FlashReadRequest_data_t data;
    Crc crc;
/* @@protoc_insertion_point(struct:FlashReadRequest) */
} FlashReadRequest;

typedef PB_BYTES_ARRAY_T(200) FlashWriteRequest_data_t;
typedef struct _FlashWriteRequest {
    BaseHeader header;
    uint32_t addr;
    FlashWriteRequest_data_t data;
    Crc crc;
/* @@protoc_insertion_point(struct:FlashWriteRequest) */
} FlashWriteRequest;

/* Default values for struct fields */
extern const uint32_t FlashWriteRequest_addr_default;
extern const uint32_t FlashReadRequest_addr_default;

/* Initializer values for message structs */
#define FlashWriteRequest_init_default           {BaseHeader_init_default, 0u, {0, {0}}, Crc_init_default}
#define FlashReadRequest_init_default            {BaseHeader_init_default, 0u, {0, {0}}, Crc_init_default}
#define FlashWriteRequest_init_zero              {BaseHeader_init_zero, 0, {0, {0}}, Crc_init_zero}
#define FlashReadRequest_init_zero               {BaseHeader_init_zero, 0, {0, {0}}, Crc_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define FlashReadRequest_header_tag              1
#define FlashReadRequest_addr_tag                2
#define FlashReadRequest_data_tag                3
#define FlashReadRequest_crc_tag                 4
#define FlashWriteRequest_header_tag             1
#define FlashWriteRequest_addr_tag               2
#define FlashWriteRequest_data_tag               3
#define FlashWriteRequest_crc_tag                4

/* Struct field encoding specification for nanopb */
extern const pb_field_t FlashWriteRequest_fields[5];
extern const pb_field_t FlashReadRequest_fields[5];

/* Maximum encoded size of messages (where known) */
#define FlashWriteRequest_size                   (221 + BaseHeader_size + Crc_size)
#define FlashReadRequest_size                    (221 + BaseHeader_size + Crc_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BOOTLOADER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
